CAPS-DGU/25-1-ClubFair-Client

- src/components/SearchBar.css
> style: Add flex grow into SearchBar

- src/App.jsx
- src/components/CommonForm.css
- src/components/CommonForm.jsx
- src/components/UseInfoField.css
- src/components/UseInfoField.jsx
- src/pages/BoothHome.css
- src/pages/BoothHome.jsx
- src/pages/EditForm.css
- src/pages/EditForm.jsx
- src/pages/Home.jsx
- src/pages/RegisterForm.css
- src/pages/RegisterForm.jsx
- 새로운 인물 등록 폼(`RegisterForm`)을 추가하고, 이와 같은 폼의 디자인에서 수정이 가능하도록 했습니다!
변경 사항
- `RegisterForm.jsx` 및 `RegisterForm.css` 추가 (새로운 사람 등록)
- 이름, 학번, 단과대, 학과 데이터를 저장하는 선택 리스트(`UseInfoField`) 추가
- 이를 기반으로하는 CommonForm (내용, 작성자란 추가)
- 위키 수정 폼(`EditForm`) 추가
- `App.jsx`에 `EditForm`과 `RegisterForm` 등록
> feat: add RegisterForm and update related components

- .github/workflows/deploy.yml
- .github/workflows/pull-request.yml
CI/CD를 위한 기본 준비를 하였습니다.
- Pull Request시 Lint 와 Build 진행
- Merge 시 deploy 진행 (aws 와의 연동은 추후에 진행할 예정)
> ci: Initialize ci/cd

- src/components/HeaderBar.jsx
- src/pages/List.jsx
Lint에서 에러가 발생하는 부분을 수정했습니다.
- 불필요한 React 의 import 삭제
- img 태그에서 herf 속성 삭제
> refactor: Resolve lint errors

- src/components/CommonForm.css
- src/components/UseInfoField.css
- src/pages/EditForm.css
- src/pages/RegisterForm.css
모바일웹뷰로만 볼 수 있었던 인물 등록, 수정 화면을 PC화면으로 볼 때 자연스러워질 수 있도록 수정했습니다.
어색하거나 잘못된 부분이 있다면 피드백 부탁드립니다!
> feat: Add PC layout support and adjust styles

- src/pages/BoothHome.jsx
- src/pages/Home.jsx
빌드 이후 이미지가 보이지 않는 현상 고침
- 이미지를 모두 import 하고 img 태그의 src 속성 수정
> fix: Resolve bug that images are not loaded after build

- .github/workflows/deploy.yml
- src/pages/AboutUs.jsx
CloudFront에서 캐시를 무효화시켜 업데이트된 페이지가 나오게 설정
- deploy.yml에 Invalidate CloudFront Cache 추가
> ci: Create cloudfront invalidation

- src/components/BackButton.css
- src/components/BackButton.jsx
- src/components/WikiMiniButton.jsx
- src/pages/AboutUs.jsx
- src/pages/BoothHome.jsx
- src/pages/Home.jsx
- src/pages/List.jsx
성능을 위해 a태그를 Link로 변경하고 몇몇을 컴포넌트화했습니다.
- a 태그 Link 태그로 변경
- WikiMiniButton 컴포넌트화
- BackButton 컴포넌트화
> feat: Replace a tag with Link, Create components

- src/pages/BoothHome.jsx
- src/pages/Home.jsx
> fix: Fix typo

- src/index.css
다크모드에서 글자가 보이지 않는 문제 수정
- index.css 에서 light 모드 관련코드로 덮어 씌우고 다크모드 속성 삭제
> fix: Resolve text visibility issue in dark mode

- src/components/WikiCard.jsx
Wiki Card 에서 넘어가는 링크 수정
- WikiCard 에서 Link되는 to 속성을 title만으로 변경 (추후에 UUID 로 변경예정)
> fix: Fix wikicard link

- src/pages/AboutUs.css
만든이 카드들을 조금 수정했습니다.
- css padding 수정
> enhancement: Fix AboutUs card

- .github/workflows/deploy.yml
> feat: Add dotenv

- src/components/WikiContent.jsx
- src/pages/BoothHome.css
- src/pages/RegisterForm.jsx
> fix: something

- src/components/SearchBar.jsx
- src/pages/BoothHome.css
- src/pages/EditForm.jsx
- src/pages/Login.jsx
- src/pages/RegisterForm.jsx
> fix: random, home link in login, booth home

- src/pages/EditForm.jsx
- src/stores/PostStore.js
> feat: Api edit

- src/components/Departments.jsx
- src/components/UseInfoField.jsx
학과 목록에서 선택되지 않아 입력이 안 되는 것을 수정
> fix: Fix departments list

- src/pages/EditForm.jsx
> fix: navigate import

- src/components/WikiContent.jsx
- src/stores/PostStore.js
> feat: Add edit,delete button

- src/pages/BoothHome.jsx
- src/pages/RegisterForm.jsx
> fix: image

- src/pages/BoothHome.css
- src/pages/List.css
- src/pages/List.jsx
> fix: list style

- src/pages/BoothHome.css
> fix: add wiki button style

- src/components/WikiContent.jsx
> fix: Uncaught Error: Invalid date format

- src/pages/BoothHome.css
> fix: media query
